### ISSUE TITLE
javanica with guice aop

### ISSUE THREAD

**Issue by raffaelespazzoli** [Netflix/Hystrix#1059]
What would be the simplest way to enhance javanica to use guice aop (https://github.com/google/guice/wiki/AOP)?

If you guys could give me some pointers I'd be happy to develop and contribute this extension.

**Comment by mattrjacobs** [comment]
@dmgcodevil Any thoughts on this approach?

**Comment by gauthamsrinivas** [comment]
We had a requirement for guice aop with Hystrix annotations. We have a fork in which we wrote guice interceptors within javanica along with a module that binds annotations appropriately. This was done because guice aop requires guice-enhanced instances of objects for method interception to work. Those who want guice aop can simply install this module into their injectors. Let me know if this approach is fine.

**Comment by raffaelespazzoli** [comment]
@gauthamsrinivas your approach seems fine to me, can you share your module and instructions on how to use it?

**Comment by mattrjacobs** [comment]
Closed due to inactivity.  Please re-open if there's more to discuss
