### ISSUE TITLE
Endless loop in HystrixMetricsStreamServlet

### ISSUE THREAD

**Issue by rocky-luo** [Netflix/Hystrix#1173]
I follow the wiki to integrate hystrix-metrics-event-stream module, when I visit http://127.0.0.1:8410/hystrix.stream it never get response. So I debug and find that the HystrixMetricsStreamServlet is in a endless loop which is:
`while (poller.isRunning() && !isDestroyed) {
    ...
}`

How can I solve this problem?

**Comment by mattrjacobs** [comment]
The intent of the `HystrixMetricsStreamServlet` is to provide data for as long as the connection to the servlet is open.  That's why it's structured as an infinite loop with a way to exit out.  

It sounds like the problem is that you're not getting a response.  When you make a request to the servlet, have you already executed commands at that point?

**Comment by rocky-luo** [comment]
I have executed some commands.When I am debugging, I can see the command infos I have executed in the variable `List<String> jsonMessages = jsonListener.getJsonMetrics();` . But it just can't get out from    the loop.

**Comment by mattrjacobs** [comment]
Since the while-loop is running in a try-catch, any sort of error will exit the loop.  One such example is the client going away.  This causes `response.getWriter().checkError()` to return true, which throws an `IOException` and exits the loop.

When I run this metrics servlet and then start a curl against it, I receive data for as long as I'm connected and the server thread is working/asleep in the `Thread.sleep` for the duration.  When I kill the curl, the above error path gets hit, and the server thread is no longer doing any work.  Have you tried something like that to observe how the pieces fit together?

**Comment by rocky-luo** [comment]
thank u, I know what's going on : )

**Comment by KumrN** [comment]
I have similar issue with hystrix 1.5.2 using on Jboss. When hitting the hystrix stream URL in browser, it's going in infinite loop and nothing is responding back to web page. I can see the metrics as JSON string in debug mode. 

whats going on ? @rocky-luo - Can you please share what was that ?
