### ISSUE TITLE
What's the point of c.n.h.c.RequestCollapserFactory.defaultNameCache

### ISSUE THREAD

**Issue by mebigfatguy** [Netflix/Hystrix#1220]
Doesn't seem to be used, but has a relatively obtuse comment attached.

**Comment by mattrjacobs** [comment]
If you look in a few other places in the codebase, `AbstractCommand`, `HystrixCollapser`, `HystrixObservableCollapser`, this pattern is used to safely turned a j.u.Class into a String once per-class, rather than on every command/collapser invocation.

So the pattern is valid, but I agree with you that the data structure you pointed out is unused.  Do you want to submit a PR with its removal, or shall I?  Thanks for all the cleanup efforts!
