### ISSUE TITLE
How to reduce the matrix frequency ?

### ISSUE THREAD

**Issue by pradeepkusingh** [Netflix/Hystrix#1257]
I am looking for a way to reduce the hystrix marix data. Can you please help me ?

**Comment by mattrjacobs** [comment]
I'm assuming you mean metrics in this question.  If so, then you want to widen the metrics window so that metrics get calculated less frequently.  You can do that by increasing the values for:

https://github.com/Netflix/Hystrix/wiki/Configuration#metrics.rollingStats.timeInMilliseconds
https://github.com/Netflix/Hystrix/wiki/Configuration#metrics.rollingPercentile.timeInMilliseconds
https://github.com/Netflix/Hystrix/wiki/Configuration#metrics.healthSnapshot.intervalInMilliseconds
