### ISSUE TITLE
Code snippet for pushing Hystrix metrics to Atlas

### ISSUE THREAD

**Issue by mukteshkrmishra** [Netflix/Hystrix#1301]
@mattrjacobs :: Do we have any code piece to show how we are pushing it to Atlas. PS: I have implemented a solution to push Hystrix Metrics to another time series and just wanted to see the Atlas implementation.

**Comment by mukteshkrmishra** [comment]
PS: I am thinking to create a generic interface which will tap all Command, ThreadPool and collapser related metrics from Hystrix Calls and then we can push into any relevant client implementation to persist it further. Your thoughts?

**Comment by mattrjacobs** [comment]
I don't know the precise mechanism that Atlas uses to get metrics off instances and into the central data store.  The level of abstraction I work at is to provide Servo Monitors, which the Atlas code can identify and move off-box.  It would likely be more effective for you to ask in the Atlas GH.

For the generic interface bit, the `HystrixMetricsPublisherCommand` / `HystrixMetricsPublisherThreadPool` / `HystrixMetricsPublisherCollapser` already exist.  They have a (very) bare-bones interface, because there are many possible things that a Hystrix user may do with those metrics.

Can you give me some more info on what sort of interfaces you would want?

**Comment by mukteshkrmishra** [comment]
Actually I have implemented these classes already and all I need is a poller implementation. Our APIs are dockerized so I am working in a pull model where apis directly thows Hystrix metrices and we have the abilty to tap them in any backend(viz: graphite, servo) using client specific implementation. I was thinking to tap all command, threadpo and collapser related metrices in a map and from there they can be send to anybackend client.

But for fetching metrices I need a poller which can poll data thrown by Hystrix (in terms of command, threadpool and collapser metrices). How can I do that.

**Comment by mattrjacobs** [comment]
I think what you want is described here: https://github.com/Netflix/servo/wiki#publishing.  I've never used this code directly (Hystrix just needs to create the Monitors), so any deeper questions would best be directed to the Servo team

**Comment by mukteshkrmishra** [comment]
These are servo specific implementation. I was thinking to implement a generic interface.

**Comment by mattrjacobs** [comment]
Sure, happy to review anything you come up with.

**Comment by mattrjacobs** [comment]
Anything more to discuss here or shall we close this?

**Comment by mukteshkrmishra** [comment]
We can close this for now.
