### ISSUE TITLE
Some question regarding HystrixCommand.Setter

### ISSUE THREAD

**Issue by mohan-mishra** [Netflix/Hystrix#1329]
We have a hystrix command group with name "XYZ" suppose. We are creating Setter as below

```
return Setter
                .withGroupKey(HystrixCommandGroupKey.Factory.asKey(commandGroupName))
                .andCommandKey(HystrixCommandKey.Factory.asKey(commandName))
                .andCommandPropertiesDefaults(
                        HystrixCommandProperties.Setter().withMetricsRollingStatisticalWindowInMilliseconds(200000)
                                .withExecutionTimeoutInMilliseconds(60000))
                .andThreadPoolPropertiesDefaults(HystrixThreadPoolProperties.Setter().withCoreSize(1));
```
This piece of code returning Setter is called at 4-5 different places from where API request is made.
Will this maintain a single thread pool based on command group or it will generate multiple thread pools because of different instance of Setter

**Comment by mattrjacobs** [comment]
Under the covers, all long-lived objects are cached per-command key.  So all commands with commandKey="XYZ" would share the same threadpool, properties, metrics, etc.

**Comment by mohan-mishra** [comment]
Just for clarification. All command groups or all commands?

**Comment by mattrjacobs** [comment]
Yeah, thread pools are not precisely like the others, so that deserves clarification.

Thread pools are static and references by name (ThreadPoolKey).  In your example above, you've left off the ThreadPoolKey, so GroupKey is used instead.

A concrete example:
Setter.withGroupKey("AAA").andCommandKey("ZZZ")
Setter.withGroupKey("AAA").andCommandKey("YYY")

would share a single thread pool named "AAA"
