### ISSUE TITLE
When does a HystrixCommand releases its thread pool?

### ISSUE THREAD

**Issue by mohan-mishra** [Netflix/Hystrix#1333]
I want to know when does a HystrixCommand releases the thread pool assigned to it when command is instantiated?
@mattrjacobs

**Comment by mattflix** [comment]
Matt Arnold here (mattflix).  Not sure which Matt you're looking for, but it is not me.  I don't work with Hystrix.

**Comment by mattrjacobs** [comment]
@mohan-mishra Hystrix works by placing the work in the `run()` method onto a Hystrix-owned thread.

If you consume the result via `T HystrixCommand.execute()`, then the Hystrix thread will be used only for the duration of the execution

If you consume the result via `Future<T> HystrixCommand.queue()`, then the Hystrix thread will be used only for the duration of the execution.

If you consume the result via `Observable<T> HystrixCommand.observe() or toObservable()`, then the Hystrix thread gets used for the execution.  Since RxJava allows fluent chaining on Observables, all further work will happen on this thread, unless you explicitly switch away.

So in the following code : `cmd.observe().map(x -> compute(x))`, the `compute` method will happen on the Hystrix thread unless you do this:
`cmd.observe().observeOn(Schedulers.computation()).map(x -> compute(x))`.

Hope that helps

**Comment by mohan-mishra** [comment]
@mattrjacobs I was of the view that if we give a thread pool size of 10 to some hystrix command, that command will assign 10 threads to itself and will not release it for someone else to take up.

**Comment by mattrjacobs** [comment]
Each command instance can only consume a single thread (on which it executes the `run()` method).  The thread pool provides a bulkhead so that only 10 of these command instances may be executing concurrently.  The 11th will find a full pool and either get queued or dropped, depending on how you've configured your system.

**Comment by mohan-mishra** [comment]
@mattrjacobs Thank you very much. One more thing, I am unable to find any proper example of how to implement request caching using hystrix.

**Comment by mattrjacobs** [comment]
https://github.com/Netflix/Hystrix/wiki/How-To-Use#Caching
