### ISSUE TITLE
How to disable Hystrix dashboard streaming ?

### ISSUE THREAD

**Issue by pradeepkusingh** [Netflix/Hystrix#1335]
We are in production and relized that we no longer need a dashboard. we want to disable streaming from app to turbine and dahsboard. How can we achieve this without any code change any properties ?

**Comment by mukteshkrmishra** [comment]
I do not think so as per current architecture there is a way to do it without having code/property changes.

Why I could think of possibly is to load HystrixMetricsStreamServlet based on some flag and value of that flag can be dynamically updated using Archiaus. But again that would require code change and needs to be changed some implementation since this servlet is an extension of HttpServlet so it can be handled in life cycle only.

Another possibility would be to load it as a bean dynamically. But these options are not available as of now.

@mattrjacobs : Your thoughts?

**Comment by mattrjacobs** [comment]
The Hystrix metrics stream relies on the SSE stream produced by the HystrixMetricsStreamServlet.  If you don't need it, then don't include the hystrix-metrics-event-stream JAR in your application, and don't reference it in your web.xml
