### ISSUE TITLE
Command execution time is not available from the hook

### ISSUE THREAD

**Issue by krutsko** [Netflix/Hystrix#1386]
Hello

We have a use case to make hystrix command instrumentation by process execution results in the our custom hook, but since hystrix 1.4 the `getExecutionTimeInMilliseconds` from `onThreadComplete` do not return a true value (it's not recorded yet). 

I've noticed that [`recordTotalExecutionTime`](https://github.com/Netflix/Hystrix/blob/1.4.x/hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java#L457) moved down to `doOnTerminate` which happened after [onThreadComplete](https://github.com/Netflix/Hystrix/blob/1.4.x/hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java#L917). Is there a reason behind this?
I think, the execution is done and time is known `onThreadComplete`.

We use Hystrix 1.4.13. 
It's working fine on 1.3.x

**Comment by mattrjacobs** [comment]
The 1.3 series is ~2 years old, so I can't really speak for the motivations in that code.

In master today (which should be fairly similar to 1.4.13 for hook purposes), the execution time is done at the end of the entire command instead of the thread execution for a couple reasons

1) If we do it at thread-complete, we don't capture fallback execution time that happens off-thread (TIMEOUT/SHORT_CIRCUITED/SEMAPHORE_REJECTED/THREAD_POOL_REJECTED)
2) If we do it at thread-complete, we have to duplicate this logic for the semaphore-isolated case.

IMO, the correct behavior is the current behavior.  If you can switch your logic to use the onSuccess/onError hooks, I think that would be preferable

**Comment by krutsko** [comment]
Thanks @mattrjacobs 

I have verified execution time recorded properly in the latest 1.5.6. But isn't working at 1.4.26 (latest 1.4.x).
Is line 1.4.x still under support /Or we should upgrade to 1.5.x ?
Any caveats on upgrade to 1.5? (I see the migration guide hasn't much info https://github.com/Netflix/Hystrix/wiki/Migration-Guide#proposed-changes-from-14x-to-15x)

**Comment by mukteshkrmishra** [comment]
So far I have not encountered any issues after upgrading to 1.5.3 or 1.5.6 . We run multiple use cases using hystrix. Also it gives you in defining various choices especially in threadpool management like configuring min and max threadpool size used by Hystrix. I would say go ahead and upgrade that after running and testing your use cases with latest version😊
