### ISSUE TITLE
Support @HystrixCommand for rx.Single and rx.Completable similar to rx.Observable

### ISSUE THREAD

**Issue by piotrturski** [Netflix/Hystrix#1403]
`@HystrixCommand` doesn't work as expected for methods that return `rx.Single` or `rx.Completable`. it would be nice to have them handled in a same way as `rx.Observable`

**Comment by piotrturski** [comment]
`@HystrixCommand` doesn't work as expected for methods that return `rx.Single` or `rx.Completable`. it would be nice to have them handled in a same way as `rx.Observable`

**Comment by mattrjacobs** [comment]
I think this could get addressed at the `hystrix-core` or `hystrix-javanica` layer.  I'm happy to review PRs for either, if anyone is interested in this.

**Comment by piotrturski** [comment]
i'm willing to try if someone can point me to classes that do that for Observable, so i can understand the architecture

**Comment by mattrjacobs** [comment]
In Javanica, the support is here: https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/GenericObservableCommand.java.

In `hystrix-core`, the class is here: https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCommand.java.

If you're interested in working on the extension to `hystrix-core`, please let me know, so I can help with design considerations.  Thanks!

**Comment by piotrturski** [comment]
of course i'm open to suggestions. after a quick look at the code, i was thinking about adding `.toSingle()` and `.toCompletable()` somewhere in `HystrixCommandAspect` or create new `ExecutionType`s. it would be perfect to just add some post-processing to existing observableCommand, but yet i don't see any quick way of doing it

**Comment by dmgcodevil** [comment]
If it's still relevant, I believe that first of all `hystrix-core` should be extended to support `Completable` , `Single` and etc. Currently it's not possible to implement it using HystrixObservableCommand because HystrixObservableCommand#construct returns `Observable`,  but `Completable` and `Observable` are different types. However, possible workaround is to add a logic to transform incompatible rx types once command action [executed](https://github.com/dmgcodevil/Hystrix/blob/8715b71b8c87968f9880d708e919496e44bf000e/hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/GenericObservableCommand.java#L72) and before passing a [result](https://github.com/dmgcodevil/Hystrix/blob/8715b71b8c87968f9880d708e919496e44bf000e/hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/aop/aspectj/HystrixCommandAspect.java#L130) to a caller. I have made some changes and pushed to my [branch](https://github.com/dmgcodevil/Hystrix/tree/iss1403). Checkout out my changes by the following [commit](https://github.com/dmgcodevil/Hystrix/commit/8715b71b8c87968f9880d708e919496e44bf000e).

**Comment by mendlik** [comment]
Hi, I stuck on the same problem - HystrixCommand with rx.Single. @dmgcodevil did you think about making a PR from your branch?

**Comment by dmgcodevil** [comment]
@mendlik basically I can, however I'm not sure that this implementation makes sense from reactive programming perspective, could you review my commit ?

**Comment by mendlik** [comment]
@dmgcodevil thanks for staying on this issue. I read your code and it looks ok to me. IMHO it's ready to become a PR.

I also agree with your comment https://github.com/Netflix/Hystrix/issues/1403#issuecomment-281218958 . It would be nice to make `hystrix-core` extendible for all kinds of reactive streams. But in the meantime your PR will make hystrix support for RxJava close to complete. Thanks.

**Comment by dmgcodevil** [comment]
This issue can be close since PR is closed
