### ISSUE TITLE
I'm writing a test cases by mocking the Hystrix call

### ISSUE THREAD

**Issue by DineshBoinapally1** [Netflix/Hystrix#1417]
I'm able to mock the Hystrix command and my test case is passing but while building my war I'm facing an error that is

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gatewayConfiguration' defined in URL [jar:file:/Users/boinapally/.m2/repository/com/***/connect/common/gateway-common/16.20.1.2/gateway-common-16.20.1.2.jar!/com/garmin/connect/common/***/config/GatewayConfiguration.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Another strategy was already registered.

Caused by: java.lang.IllegalStateException: Another strategy was already registered.

The lines of code I added in my test-applicationContext.xml is : <context:component-scan base-package="com.garmin.connect.common.gateway.config"/>

and for in every test method the two lines I used to mock my Hystrix call is:

 HystrixRequestContext.initializeContext();
HystrixRequestContext.getContextForCurrentThread().shutdown();

Any solutions please

**Comment by mattrjacobs** [comment]
The error is occurring because you've got multiple code paths that are attempting to set up some static (singleton) data structures that Hystrix needs to operate.

If you want to understand why that's occurring, it would be useful to add breakpoints to all of the `HystrixPlugins.register*` methods.  Generally, it's the case that some init logic is running at the same time as commands executing.  Whenever this occurs, if the commands find a necessary null data structure, the command initializes it with a default.  Then the init logic runs and shows the error message you see.  If this is the case, then the fix is to make sure that all init logic runs before any command runs.  The specifics of that vary, depending on your exact situation.

Also see [Operational FAQ](https://github.com/Netflix/Hystrix/wiki/FAQ%20:%20Operational)

**Comment by DineshBoinapally1** [comment]
Thank you so much for the response. fixed it by resting the hystrix call before executing the each test case and then performing the mocking option helped me to solve. one issue I faced is the service I'm working is using different dependency during the runtime compared to  compile time. fixed it by excluding the runtime dependency in gateway-common .

**Comment by mattrjacobs** [comment]
I'm not familiar with gateway-common - that sounds custom to your setup.  In any case, glad you got it resolved
