### ISSUE TITLE
Hystrix.reset() not refreshing state.

### ISSUE THREAD

**Issue by praharsh10** [Netflix/Hystrix#1429]
I am running hystrix as circuit breaker with the following properties. 

properties.withExecutionTimeoutInMilliseconds(10000);		//10 seconds		
properties.withCircuitBreakerSleepWindowInMilliseconds(600000); 	//10 mins	
properties.withCircuitBreakerRequestVolumeThreshold(10);	
properties.withCircuitBreakerErrorThresholdPercentage(80);			//80%
properties.withMetricsRollingStatisticalWindowInMilliseconds(300000);	//5 mins
properties.withMetricsRollingStatisticalWindowBuckets(10);	 						

After circuit breaks for a particular command key, i call refresh.
On calling the same command key again, i'm still with an open circuit and have to wait the remaining of the 10 minutes for the circuit to close again. 

Also, please give me a way to achieve the above if i have the wrong understanding of Hystrix.reset()

**Comment by praharsh10** [comment]
Seems it didnt work in a particular environment.

**Comment by mattrjacobs** [comment]
These values are significantly different from the defaults.  Is there a reason you've chosen to make them this high?

Also, it's not intended to call `Hystrix.reset()` anywhere outside of unit tests.  (I think that's what you meant when you typed `refresh`).  Ideally, you would configure Hystrix such that automatic recovery happens without manual intervention.  That's why the defaults being high is concerning.

**Comment by praharsh10** [comment]
For my usecase, the backend components are not hit with the same frequency. Some are hit less, like 3 calls per minute, some are very high upto 3k calls per minute. To take care of all these i chose the above values. Different values of MetricsRollingStatisticalWindowInMilliseconds and MetricsRollingStatisticalWindowBuckets for different components should have been better ?

Further i have given the option to change these properties (reading from database) dynamically. Once some property is changed, i would like hystrix to reflect these properties change. For that i intend to use Hystrix.refresh(), to clear any current command properties, so that new properties reflect, without the need to restart the application. Is such use of reset recommended? or is there another way i can use?

**Comment by mattrjacobs** [comment]
I don't recommend that you use Hystrix.reset() programatically anywhere but in unit tests.

For a service that is called at 3 requests per minute, that puts very little stress on the system.  I don't think that circuit-breaking helps at all at that volume.  Circuit-breaking is intended to relieve stress on a downstream system that's underwater.  At 3 requests/minute, that's not the case.  Hystrix has default configuration of a certain volume that must be met for circuit-breaking to apply, and I would leave that as-is.

For higher-volume circuits, it's better to rely on circuits transitioning from open back to closed automatically, rather than any sort of manual intervention.  Circuit-breaking works as follows:

1) If volume and error rate both meet the required thresholds, then the circuit-transitions from CLOSED->OPEN
2) For the duration of the sleep window, this command fails fast with a SHORT_CIRCUITED status, and no calls are made downstream.
3) After the sleep window, a single call is allowed through.  If it succeeds, then the circuit transitions from OPEN->CLOSED.  If it does not, it stays OPEN and sleeps for another round of the sleep window.  This repeats indefinitely.

So recovery should always be automatic and governed by configuration.

**Comment by praharsh10** [comment]
Ok, so there is no way of changing the properties associated with an already created instance of HystrixCommandKey during runtime?
I require this as i am giving the backend APIs the functionality to change their executionTimeout, and the change should be reflected without the need to restart the application.

**Comment by mattrjacobs** [comment]
Yes, please look at [the Hystrix config wiki](https://github.com/Netflix/Hystrix/wiki/Configuration#introduction).  We use Archaius for the ability to dynamically change properties without restarting the application.
