### ISSUE TITLE
Make it possible to learn execution isolation strategy for the current command in HystrixConcurrencyStrategy

### ISSUE THREAD

**Issue by dmak** [Netflix/Hystrix#1564]
I suggest to pass `HystrixCommandProperties` or `ExecutionIsolationStrategy` to `HystrixConcurrencyStrategy#wrapCallable(Callable callable)`. For example, if `ExecutionIsolationStrategy` is `SEMAPHORE` then in my case the given callable can be returned as is, without being wrapped:

```java
HystrixPlugins.getInstance().registerConcurrencyStrategy(new HystrixConcurrencyStrategy() {
    @Override
    public <T> Callable<T> wrapCallable(Callable<T> callable, ExecutionIsolationStrategy strategy) {
        if (strategy == ExecutionIsolationStrategy.SEMAPHORE) {
            return callable;
        }
        return new MyCallable<T>(callable);
    }
});
```

**Comment by mattrjacobs** [comment]
Something similar came up in /#1548#1570, in which Hystrix was eagerly calling `wrapCallable`.  After that change, it will now invoke `wrapCallable` only when:

* putting the Hystrix-wrapped work onto a Hystrix thread (command is thread-isolated)
* executing the fallback on a HystrixTimer thread
* executing a HystrixCollapser-produced command on a HystrixTimer thread

So I don't believe that `wrapCallable` ever gets invoked on the user-provided work when the command is semaphore-isolated.

**Comment by dmak** [comment]
I agree. After doublechecking I confirm that `wrapCallable` is called only from pool thread.

**Comment by JagmohanSharma** [comment]
@mattrjacobs I have one question about this change. As in case of hystrix command time out when executing fallback on HystrixTimer thread, as mentioned above , it will now invoke wrapCallable.

So does this will also make call to  wrapped callable's call() method?  

In our case we are passing MDC context between threads using call() method-

        public K call() throws Exception {
        try {
            if (parentMDC != null && !parentMDC.isEmpty()) {
                MDC.setContextMap(parentMDC);
            }
            return actual.call();
        } finally {
            MDC.clear();
        }
    }

but this is not being set in case of hystrix time out when fallback is being executed on Hystrix Timer thread. is this expected behaviour? Excuse me for commenting on a closed issue.
