### ISSUE TITLE
Requests that end up with a HystrixBadRequestException are not visible in Dashboard traffic

### ISSUE THREAD

**Issue by pparth** [Netflix/Hystrix#186]
Hello,

I used HystrixBadRequestException in order to differentiate between the 4XX http errors and the 5XX ones, when wrapping an http client using a Hystrix command. I can see in the Dashboard that these requests do not count as Exceptions. But to my surprise, i also see that they do not count at all! So, we have this weird thing where the requests are properly monitored in the Pool traffic, but there is not traffic in the relevant Command. If we accept that these are client-side errors, then i would assume that they should be countered as Succeeded. Is this a bug or maybe i am missing something important in the whole rationale?

**Comment by mattrjacobs** [comment]
I just added a metric to track HystrixBadRequestExceptions.  If anyone is interested in adding it to the dashboard, please submit a PR.

**Comment by mattrjacobs** [comment]
The change in #776 adds the existing bad request metric to the dashboard (in the lower left-hand corner with the color of lightSeaGreen).  No semantics of command operation were touched

**Comment by yoorick** [comment]
Hello,

I have a question, why the added `badRequests` counter [still doesn't count towards](https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandMetrics.java#L420)  `totalRequestCount`.
Was this an intentional decision? If yes, what's the reason behind that?

Today, in case of any significant amount of Bad Requests, you get misleading numbers in the metrics stream like that:
```
{
  "errorPercentage": 50,
  "errorCount": 16,
  "requestCount": 32,
  "rollingCountBadRequests": 30,
  "rollingCountExceptionsThrown": 30,
  "rollingCountFailure": 16,
  "rollingCountSuccess": 16,
  ...
}
```
You can see that real request count in this example is 62. (And real errorPercentage is either ~25% or ~75%, depending on how to treat bad requests, but not 50%).
