### ISSUE TITLE
1.4: executionTimeout property for async

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/Hystrix#300]
We need a property on the semaphore isolated path for timeout now that we support async timeout.

Currently in the 1.4 RCs it uses the threadIsolated property for both, but that's confusing to set it for semaphoreIsolated configs.

**Comment by mattrjacobs** [comment]
@KoltonAndrus I don't see this property referenced anywhere in the execution flow.  Are you able to pick this back up and get that wired in?

**Comment by mattrjacobs** [comment]
After further thought, I think the ideal design is to have 1 timeout value defined, regardless of whether the command is sempahore- or thread-isolated.  

Since only the async timeout mechanism is used now (as of #579), it's straightforward to wire a signal timeout into the AbstractCommand flow.  The only interesting thing is the configuration API.  My view is that the config setting should be agnostic of semaphore or thread isolation, and the config that is thread-specific (```HystrixCommandProperties.executionIsolationThreadTimeoutInMilliseconds```) should be deprecated.

**Comment by mattrjacobs** [comment]
Closed by #664
