### ISSUE TITLE
HystrixCommand.execute()/queue() are final in Hystrix 1.4.0

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#715]
Reported in https://twitter.com/pdavidso/status/578698214011838464.

**Comment by mattrjacobs** [comment]
Looks like this got introduced fairly early in the 1.4.0 release cycle: https://github.com/Netflix/Hystrix/commit/93c82407#diff-24e496c440c4e53f17f1eedfed87fc1fL127

/cc @benjchristensen

**Comment by pdavidson** [comment]
Thanks for opening this @mattrjacobs.  

The change breaks mocking HystrixCommands with Mockito since Mockito cannot mock final methods.  (https://github.com/mockito/mockito/wiki/FAQ)

Typically, I use a CommandFactory to create the HystrixCommand objects so when testing the code interacting with the HystrixCommand, the CommandFactory can return a Mockito mock HystrixCommand.  

Currently to work around this, I subclass my command and override the run() method with custom mock logic.  This technique works fine for execute(), but queue() becomes more tricky dealing with the future in the unit test, especially if not waiting for the result.

**Comment by mattrjacobs** [comment]
My inclination is to make these non-final and cut a 1.4.1 release.  I don't see a reason why these methods have to be final, and breaking backwards-compatibility was not intended.  

Any reason not to do this?

**Comment by benjchristensen** [comment]
I agree. It seems accidental as we don't want to break backwards compatibility.

**Comment by mattrjacobs** [comment]
Released as 1.4.1: https://github.com/Netflix/Hystrix/releases/tag/v1.4.1
