### ISSUE TITLE
Why do so few types override equals?

### ISSUE THREAD

**Issue by gsmith85** [Netflix/Hystrix#765]
Many of the types in the Hystrix project don't override `equals`.  Is there a reason why this is?

I have a test where I'm attempting to verify that a `HystrixThreadPoolProperties.Setter` instance returned by method is configured as I'd expect, however the only way to do that in full, without an equals method, is asserting against each field in `HystrixThreadPoolProperties.Setter`, which isn't particularly convenient.

I realize that generating and maintaining `equals` and `hashCode` can be cumbersome, but particularly as Guava is a project dependency, the helper methods it provides could be leveraged to deliver this functionality where appropriate.

**Comment by mattrjacobs** [comment]
Yeah, this seems like a good change.  

A minor correction - Hystrix does not have a dependency on Guava, so these would have to be hand-rolled.

**Comment by mattrjacobs** [comment]
A comment here - most classes do not override equals because we don't want equality other than reference equality.  For example, HystrixCommand instances are all different, even if constructed in the exact same way.  Some other classes are effectively singletons due to caching, so reference equality is also appropriate (like HystrixCommandProperties/HystrixCommandMetrics).

**Comment by mattrjacobs** [comment]
I'm happy to review a change here.  So far, I haven't felt any pain from missing equals() methods, so I haven't spent anytime on working on a PR.
