### ISSUE TITLE
Javanica: requestLog.enabled property is not respected in AbstractCommand

### ISSUE THREAD

**Issue by chornyi** [Netflix/Hystrix#782]
When using Javanica, command properties are not passed to the constructor of `AbstractCommand` and therefore all default values are used there. In particular the `requestLog.enabled` is always evaluated to `true` here: https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java#L263

This breaks the feature that was implemented in https://github.com/Netflix/Hystrix/pull/724

First the `super()` constructor is called and only then `commandProperties` are set: https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/AbstractHystrixCommand.java#L55-L57

**Comment by mattrjacobs** [comment]
@dmgcodevil Any thoughts on this one?

**Comment by dmgcodevil** [comment]
Hi @chornyi 
Yes, I hear you man. I think the reason why I implemented setting properties using 
``` ConfigurationManager.getConfigInstance().setProperty ```
because the fields

```java
protected HystrixCommandProperties.Setter commandPropertiesDefaults;
protected HystrixThreadPoolProperties.Setter threadPoolPropertiesDefaults;
```
 weren't in Setter class at that moment and were added latter, I don't know when those fields were added exactly, but looks like using ``` ConfigurationManager.getConfigInstance().setProperty ``` isn't good idea because some properties used when command constructor invoked. I'll fix this

**Comment by dmgcodevil** [comment]
@mattrjacobs please close this issue
