### ISSUE TITLE
Javanica: HystrixCommandAspect not able to get generic class type

### ISSUE THREAD

**Issue by vibhaanshu** [Netflix/Hystrix#784]
I'm using hystrix command on a class which is implementing generic interface. HystrixCommandAspect is not able to retrieve the parameter types of the child class.
```
public interface IHelloComponent <K, T>{  
        public String getValue(final K key, final T value);
        public String defaultValue(final K key, final T value);
    }

@Service
public class HelloComponent implements IHelloComponent<String, String>{
    @Override
    @HystrixCommand(fallbackMethod = "defaultValue")
    public String getValue(final String key, final String value){
        if(true)
        throw new RuntimeException();
        return "Hello";
    }
    public String defaultValue(final String key, final String value){
        return "default";
    }
```
Inside `HystrixCommandAspect` Method value is coming as `public java.lang.String HelloComponent.getValue(java.lang.Object,java.lang.Object)`. Because of this it throws error `hystrixCommand cannot be null`.

**Comment by mattrjacobs** [comment]
@dmgcodevil Any thoughts on this one?

**Comment by dmgcodevil** [comment]
Not so far but I'll check it.

**Comment by dmgcodevil** [comment]
@vibhaanshu  you have this problem because you use JDK proxy in spring. Actually if you have interace for bean than spring atomatically creates proxy using JDK, otherwise cglib. Proxy created using jdk doesn't have information about annotations. You should use cglib proxies instead of jdk.

**Comment by vibhaanshu** [comment]
Thanks

**Comment by dmgcodevil** [comment]
@vibhaanshu hold on. I was convinced that javanica works fine with jdk proxy and I'm sure that I did some work to have it works. ProceedingJoinPoint has two methods: getThis() returns proxy, but getTarget() returns real object and we can get real type. So jdk proxies shouldn't be a problem but it is not true and let me explain why .I spent couple hours to figure out. I found the root cause of the issue. Java creates bridge methods for methods with generics (I forgot about that...):

```java
public static Class[] getParameterTypes(JoinPoint joinPoint) {
        MethodSignature signature = (MethodSignature) joinPoint.getSignature();
        Method method = signature.getMethod();
        return method.getParameterTypes();
    }

``` 

this code returns paramter types for bridge method and results to array with raw types, i.e. array Objects.
Calling ``` java type.getDeclaredMethod(methodName, parameterTypes); ``` returns bridge method that doesn't have any annotations. It happens because we need to pass generic types to get appropriate method but not raw types. I added the [ability](https://github.com/dmgcodevil/Hystrix/blob/javanica-iss-926/hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/MethodProvider.java) to get original method instead of bridge and now it works now. Created [PL (https://github.com/Netflix/Hystrix/pull/957/files)
