### ISSUE TITLE
Additional warmup command timeout parameter

### ISSUE THREAD

**Issue by lazycodeninja** [Netflix/Hystrix#810]
We've been experiencing the same issue that was described [here](https://groups.google.com/forum/#!topic/hystrixoss/_jnxAyS20lA), where the first invocation of a Hystrix command times out and fails.  

In that thread it's mentioned that handing/ignoring this warmup jitter is handled by Ribbon but we're not looking to use Ribbon at this stage (not sure it will fit in our current topology).  All we really need is a more generous timeout for the first request for that command.  Would it be possible to create an additional configuration parameter that specifies a "warmup" timeout buffer?

**Comment by benjchristensen** [comment]
Warmup is not about the HystrixCommand, it is instead about the network connections a HystrixCommand may use. Adding a warmup timeout to Hystrix itself would not solve the problem, as it wouldn't only apply the first time. Since almost all non-trivial uses of Hystrix involve connection pools, many connections, and connections coming-and-going, Hystrix is the wrong place to put this type of logic. 

The underlying connection pool should handle this behavior. This is similar to how Hystrix does not do retries, and how Hystrix is completely unaware of how IO is done.
