### ISSUE TITLE
CorrelationId

### ISSUE THREAD

**Issue by cforce** [Netflix/Hystrix#841]
The idea is to be able to track every request going through the microservices landscape. Therefor every request must get marked by an unqiue id, the correlationId. Furthermore to find out in which order the request choose its way through the microservices we need to increase an counter on every hystrix call. Every call will write to log (eg. logstash, es) and we can query finding requests with the same correlationd id and order it asc via the counter to see which microservices it passed on its way.
It would be great if hyxtrix command can be extended to add correleationId (if not already present) to 
every request and increase the counter.

The collected data could be be taken to create  live depency and tracking view of request. An edge from microservice to microservice will get as more bold as many request flow through this pipe in relation to the ammount of requests all over.

**Comment by mattrjacobs** [comment]
@cforce - We do something similar at Netflix, but we don't use Hystrix as the implementation mechanism.  We have a system similar to Google Dapper/Twitter Zipkin that does distributed tracing, much like you've described.  We've found it more practical to do it at the networking layer (for Netflix that is Ribbon: https://github.com/Netflix/ribbon).  This is because Hystrix may be arbitrary work, whereas instrumenting at the network layer gives us exactly what we want.

The HystrixRequestVariable class already exists, and may be used to pass state between threads on a single JVM.  I think a networking library is a more appropriate home for passing state to an off-box system.

**Comment by cforce** [comment]
We are also want to use Ribbon (via Feign) to do the Balanced Rest Call after Lookup. I wasn't aware that there is already an CorrelationId Feature available. Can you point me to the documentation/code/examples how this works/ has to be used? How do you persist and collect the data afterwards for single request tracking and mass (stats) - eg.g like the tracking graph i described?

**Comment by mattrjacobs** [comment]
It looks like the correlation ID is a feature that has not made it to OSS yet.  I'd suggest submitting an issue to Ribbon/Karyon, as I believe that's a more appropriate home for this feature.

**Comment by cforce** [comment]
done. https://github.com/Netflix/ribbon/issues/238
