### ISSUE TITLE
Javanica: What is the purpose behind the closure in Javanica?

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#846]
/cc @dmgcodevil 

crosspost from: https://groups.google.com/forum/#!topic/hystrixoss/qwzYV15e8FA

**Comment by mattrjacobs** [comment]
Closing due to age.  Please re-open if you'd like to continue the discussion

**Comment by dmgcodevil** [comment]
Answered in original post:

 The reason why we need to wrap method logic in AsyncResult is because you can't return any types if a method return type is Future, your should return something compatible with Future type, like subclass of Future and so on.  AsyncResult it's just a stab, fake implementation of Future, so what ClosureFactory does, it creates new instance of AsyncResult and it doesn't execute any logic within invoke method at the point, it doesn't call "invoke" method to be precise. Logic within invoke method is executed only within HystrixCommand and client gets real Future that HystrixCommand returns, like when a client invokes queue() on HystrixExecutable using regular HystrixCommand.
