### ISSUE TITLE
add property to dynamically disable hystrix 

### ISSUE THREAD

**Issue by tol** [Netflix/Hystrix#908]
Hi,

Is there a way to completely disable hystrix dynamically?
When the property is activated, HystrixCommand should just forward the request to the embedding code (no thread pool, async execution etc ) .

Thank you,

**Comment by mattrjacobs** [comment]
Hystrix itself doesn't support this.  Note that HystrixCommands may be executed to return a `T`, `Future<T>`, or `Observable<T>`.  The `run()` method returns a `T`.  So in your code, you could only replace usages of `cmd.execute()` with the run method for your code to make sense.

If you wanted this functionality, you could use branch on a config value to write code like:

```java
Foo result;
if (shouldUseHystrix) {
    result = cmd.execute();    
} else {
    result = runMethod();
}
```

**Comment by mattrjacobs** [comment]
@tol I don't think there is anything to include in the Hystrix library here.  Please re-open if you'd like to discuss further.

**Comment by rorycurtis** [comment]
I was looking for the same global enabled/disabled toggle and figured that it might be a useful enhancement for Hystrix. 

The above "if" check will obviously work, though rather than having it around every HystrixCommand invocation, could something like this be implemented:

`new MyHystrixCommand(HystrixCommandGroupKey group, Callable c)`

The `execute()` method can then decide to either create a new HystrixCommand object and execute it, or simply delegate to `c.call,` if Hystrix is disabled.

**Comment by mattrjacobs** [comment]
The problem with delegating to the `run()` method is that the delegation only makes sense for `HystrixCommand.execute()`.  In the case of `queue()` or `observe()`, the choices are : 

1. Synchronously call `run()` on the caller thread and then wrap in a `j.u.c.Future` or `rx.Observable`.
2. Use a real Hystrix thread pool to get an async `Future`/`Observable`.

Option 1 would not work for many applications (including the one I work on), as it changes where work happens rather dramatically.  Option 2 starts to get fuzzy about what disabling Hystrix really means.

Any thoughts on what use cases are served by disabling Hystrix and how to achieve them, in light of my point above?

**Comment by rorycurtis** [comment]
I guess Feature Flagging is an obvious example. Adding Hystrix monitoring to our integration points is a feature for us and something that gets rolled out over time. We probably have half a dozen different integration points, resulting in 12-15 different calls that need wrapped. So not massive by any means but enough to make you think about adding the same if statement to every invocation. The integrations increase over time, as we integrate with other services.

Also, we tend to build software components in a way that most of it can be tweaked/disabled dynamically at runtime. Sometimes, we don't actually know all the use cases up front, for why a particular property might need changed, or why a particular feature might need disabled. Having the flexibility to do it though, has proven to be invaluable many times over the years.

I appreciate that I can tweak the HystrixCommand settings dynamically. I could tweak them in such a way, as to effectively disable Hystrix monitoring ...

hystrix.command.default.execution.timeout.enabled=false 
hystrix.command.default.circuitBreaker.enabled=false
...

However, the object creation, caching, etc is still going on behind the scenes. There is really no way to bypass it, which got me thinking and is how I ended up here :-)

Perhaps just tweaking those settings is all we'll ever need, if someone decides that we need to "turn Hystrix off", for whatever reason. Given what you've said, tweaking the settings or adding if checks might be the only viable option. It's just slightly more painful than Hystrix being able to figure it out by itself :-)

**Comment by mattrjacobs** [comment]
Yeah, a reasonable interpretation of "turning off Hystrix" is:

1) Skip fallback
2) Never timeout
3) Never semaphore reject
4) Never threadpool reject
5) Never short-circuit

Since part of HystrixCommand's API implies that it takes synchronous work and makes it asynchronous, Hystrix would still need to schedule work in a threadpool.  To achieve 4), Hystrix would need to use an unbounded threadpool (instead of the fixed-size one it uses today in normal operation).

If you'd like to submit a pull request that adds a new config value (hystrix.enabled?) and wires it up to all of those decision points, I'd be happy to take a look at it.
