### ISSUE TITLE
Dashboard question related to delay.

### ISSUE THREAD

**Issue by viktor76** [Netflix/Hystrix#909]
Hi, 
Is it possible to configure dashboard with considerable delay of 10 or 20 minutes?
Does it make sense at all? I have tried to do that with delay of 1 minute and the following error occurred:
"Unable to connect to Command Metric Stream."
My idea is that I want to see all failures that happened for a more long period of time. 

Thanks in advance,
Deyan

**Comment by mattrjacobs** [comment]
The delay parameter only controls how frequently to poll the app containing Hystrix metrics.  

The app with Hystrix metrics only keeps track of a fairly short duration of data.  The default is 10 seconds (https://github.com/Netflix/Hystrix/wiki/Configuration#metrics.rollingStats.timeInMilliseconds).  This is short so that the amount of memory/CPU used to store/keep track of metrics doesn't overwhelm your application.  Of course, you are free to adjust this setting.

It sounds like your use case requires a time-series database that can handle metrics persistence.  Hystrix offers modules which integrate with Servo/Yammer metrics directly, and raw streams which can be directed into a persistence layer (instead of solely the dashboard).  Once you persist those metrics, you can bound the amount in your Hystrix application quite tightly and use the persisted metrics for all other queries.

**Comment by viktor76** [comment]
Hi, 
This is exactly what I was looking for.
Thank you very much and best regards,
Deyan

**Comment by titojoseph** [comment]
Hi mattrjacobs,

We have already integrated Hystrix with JMX.Need to perform snapshotting our Hystrix command metrics every 1 second. Provided below configuration properties to achieve the same

hystrix.command.default.metrics.rollingStats.timeInMilliseconds = 1000;
hystrix.command.default.metrics.rollingStats.numBuckets = 10;

That will keep all RollingNumbers (counters) for 1000ms (1 sec) in .01 second increment (1000ms /10 == 100ms).

At any point in time when you request a metric it will give you the count for last 1 second (100ms*10) with the bucket rotating each 0.01 second.. But the metrics getting refreshed only in default 10 seconds, not the custom set 1 second window. Could you please advice.
