### ISSUE TITLE
Testing with ObservableResult

### ISSUE THREAD

**Issue by gorelikov** [Netflix/Hystrix#980]
I have code that uses ObservableResult in method annotated by @HystrixCommand.
So, i tried to test this code but got endlessly working test. I mean, code wrapped by ObservableResult even not performed.
What i'm doing wrong? Are there any details in ObservableResult that denies it testing?
I have little more complex test and logic  but for example:
Method:
```java
 @Override
  @HystrixCommand
  public Observable<TokenDTO> authorize(String authHeader, String body) {
    return new ObservableResult<TokenDTO>() {
      @Override
      public TokenDTO invoke() {
        //do something
      return requester.implicitAuthz(authHeader, body);
      }
    };
  }
```
and test:
```java
class AuthControllerTest extends Specification {

  @Subject
  AuthController controller;
  def requester = Mock(OAuthRequester)
  
  def setup() {
    def authService = new OAuthService(requester, USERNAME, PASSWORD, SECRET)
  }

  def 'should successfully get tokens'() {
    when:
    def res = controller.auth(USERNAME, PASSWORD).toBlocking().single()
    then:
    2 * requester.implicitAuthz(_, _) >> new TokenDTO()
    //assert something
  }
}
```

**Comment by dmgcodevil** [comment]
Hi. ObservableResult  is deprecated because of the reasons mentioned [here](https://github.com/Netflix/Hystrix/issues/729) and [here](https://github.com/Netflix/Hystrix/issues/948), and I already have PL fot this, so ObservableResult will be removed soon ([here](https://github.com/dmgcodevil/Hystrix/blob/master/hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/observable/BasicObservableTest.java) you can find a  test that shows how observable looks like in new way in javanica). In the meatime if you need observable then wrap a method annotated with @HystrixCommand in observable, something simple like Observable.just of from. It's not a solution of your problem but just a notice. Getting back to our problem. Are you sure that annotated method is catched by javanica aspect? Maybe you missed something in your config (I don't know that you're using to weave your code with javanica aspects) ?

**Comment by gorelikov** [comment]
Thank you. I have already understand principle of ObservableResult.
